version: '3.7'

services:
  db:
    image: postgres:13.3
    container_name: webpegas_pg
    env_file: .env



  app:
    build:
      context: .
    env_file: .env
    container_name: webpegas_app
    command: ['/test_task_for_webpegas/docker/app.sh']
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./alembic:/test_task_for_webpegas/alembic
      - ./src:/test_task_for_webpegas/src


